CREATE DATABASE OLIST_DB;
CREATE SCHEMA OLIST_DB.RAW;
CREATE WAREHOUSE OLIST_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

Use WAREHOUSE OLIST_WH;
USE DATABASE OLIST_DB;
USE SCHEMA RAW;

SELECT 'CUSTOMERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW.CUSTOMERS
UNION ALL SELECT 'ORDERS', COUNT(*) FROM RAW.ORDERS
UNION ALL SELECT 'ORDER_ITEMS', COUNT(*) FROM RAW.ORDER_ITEMS
UNION ALL SELECT 'ORDER_PAYMENTS', COUNT(*) FROM RAW.ORDER_PAYMENTS
UNION ALL SELECT 'ORDER_REVIEWS', COUNT(*) FROM RAW.ORDER_REVIEWS
UNION ALL SELECT 'PRODUCTS', COUNT(*) FROM RAW.PRODUCT
UNION ALL SELECT 'SELLERS', COUNT(*) FROM RAW.SELLERS
UNION ALL SELECT 'GEOLOCATION', COUNT(*) FROM RAW.GEOLOCATION
UNION ALL SELECT 'CATEGORY_TRANSLATION', COUNT(*) FROM RAW.CATEGORY_NAME;

CREATE SCHEMA OLIST_DB.STAGING;   -- silver: cleaned, typed data
CREATE SCHEMA OLIST_DB.MARTS;     -- gold: business-ready tables for analysis/BI