USE DATABASE OLIST_DB;
USE SCHEMA RAW;

CREATE SCHEMA IF NOT EXISTS OLIST_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS OLIST_DB.MARTS;


-- 1. ORDERS
CREATE OR REPLACE TABLE OLIST_DB.STAGING.ORDERS AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    ORDER_PURCHASE_TIMESTAMP AS PURCHASE_TS,
    ORDER_APPROVED_AT AS APPROVED_TS,
    ORDER_DELIVERED_CARRIER_DATE AS DELIVERED_CARRIER_TS,
    ORDER_DELIVERED_CUSTOMER_DATE AS DELIVERED_TS,
    ORDER_ESTIMATED_DELIVERY_DATE AS ESTIMATED_DELIVERY_TS
FROM OLIST_DB.RAW.ORDERS
WHERE ORDER_ID IS NOT NULL;


-- 2. ORDER ITEMS
CREATE OR REPLACE TABLE OLIST_DB.STAGING.ORDER_ITEMS AS
SELECT
    ORDER_ID,
    ORDER_ITEM_ID,
    PRODUCT_ID,
    SELLER_ID,
    SHIPPING_LIMIT_DATE AS SHIPPING_DATE,
    PRICE,
    FREIGHT_VALUE
FROM OLIST_DB.RAW.ORDER_ITEMS
WHERE ORDER_ID IS NOT NULL
  AND PRODUCT_ID IS NOT NULL;


-- 3. ORDER PAYMENTS
CREATE OR REPLACE TABLE OLIST_DB.STAGING.ORDER_PAYMENTS AS
SELECT
    ORDER_ID,
    PAYMENT_SEQUENTIAL,
    PAYMENT_TYPE,
    PAYMENT_INSTALLMENTS,
    PAYMENT_VALUE
FROM OLIST_DB.RAW.ORDER_PAYMENTS
WHERE ORDER_ID IS NOT NULL;


-- 4. CUSTOMERS
CREATE OR REPLACE TABLE OLIST_DB.STAGING.CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_UNIQUE_ID,
    CUSTOMER_ZIP_CODE_PREFIX,
    INITCAP(CUSTOMER_CITY) AS CUSTOMER_CITY,
    UPPER(CUSTOMER_STATE) AS CUSTOMER_STATE
FROM OLIST_DB.RAW.CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL;


-- 5. SELLERS
CREATE OR REPLACE TABLE OLIST_DB.STAGING.SELLERS AS
SELECT
    SELLER_ID,
    SELLER_ZIP_CODE_PREFIX,
    INITCAP(SELLER_CITY) AS SELLER_CITY,
    UPPER(SELLER_STATE) AS SELLER_STATE
FROM OLIST_DB.RAW.SELLERS
WHERE SELLER_ID IS NOT NULL;


-- 6. PRODUCTS
CREATE OR REPLACE TABLE OLIST_DB.STAGING.PRODUCTS AS
SELECT
    PRODUCT_ID,
    COALESCE(PRODUCT_CATEGORY_NAME, 'unknown') AS PRODUCT_CATEGORY,
    PRODUCT_WEIGHT_G,
    PRODUCT_LENGTH_CM,
    PRODUCT_HEIGHT_CM,
    PRODUCT_WIDTH_CM
FROM OLIST_DB.RAW.PRODUCT
WHERE PRODUCT_ID IS NOT NULL;


-- 7. GEOLOCATION
CREATE OR REPLACE TABLE OLIST_DB.STAGING.GEOLOCATION AS
SELECT
    GEOLOCATION_ZIP_CODE_PREFIX AS ZIP_CODE_PREFIX,
    AVG(GEOLOCATION_LAT) AS LAT,
    AVG(GEOLOCATION_LNG) AS LNG
FROM OLIST_DB.RAW.GEOLOCATION
GROUP BY GEOLOCATION_ZIP_CODE_PREFIX;


-- 8. ORDER REVIEWS
CREATE OR REPLACE TABLE OLIST_DB.STAGING.ORDER_REVIEWS AS
SELECT
    REVIEW_ID,
    ORDER_ID,
    REVIEW_SCORE,
    REVIEW_COMMENT_TITLE,
    REVIEW_COMMENT_MESSAGE,
    REVIEW_CREATION_DATE AS REVIEW_CREATION_TS,
    REVIEW_ANSWER_TIMESTAMP AS REVIEW_ANSWER_TS
FROM OLIST_DB.RAW.ORDER_REVIEWS
WHERE ORDER_ID IS NOT NULL;