USE DATABASE OLIST_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE MARTS.FCT_ORDERS AS
SELECT
    o.ORDER_ID,
    o.CUSTOMER_ID,
    o.ORDER_STATUS,
    o.PURCHASE_TS,
    o.DELIVERED_TS,
    o.ESTIMATED_DELIVERY_TS,
    DATEDIFF('day', o.ESTIMATED_DELIVERY_TS, o.DELIVERED_TS) AS DELIVERY_DELAY_DAYS,
    CASE
        WHEN o.ORDER_STATUS = 'delivered' AND o.DELIVERED_TS > o.ESTIMATED_DELIVERY_TS THEN 1
        WHEN o.ORDER_STATUS = 'delivered' THEN 0
        ELSE NULL
    END AS IS_LATE,
    oi.ORDER_VALUE,
    oi.FREIGHT_TOTAL,
    oi.ITEM_COUNT
FROM STAGING.ORDERS o
JOIN (
    SELECT ORDER_ID, SUM(PRICE) AS ORDER_VALUE, SUM(FREIGHT_VALUE) AS FREIGHT_TOTAL, COUNT(*) AS ITEM_COUNT
    FROM STAGING.ORDER_ITEMS
    GROUP BY ORDER_ID
) oi ON o.ORDER_ID = oi.ORDER_ID;

CREATE OR REPLACE TABLE MARTS.CUSTOMER_RFM AS
WITH REFERENCE_DATE AS (
    SELECT MAX(PURCHASE_TS) AS MAX_DATE FROM STAGING.ORDERS
),
CUSTOMER_ORDERS AS (
    SELECT
        c.CUSTOMER_UNIQUE_ID,
        o.ORDER_ID,
        o.PURCHASE_TS,
        f.ORDER_VALUE
    FROM STAGING.ORDERS o
    JOIN STAGING.CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
    JOIN MARTS.FCT_ORDERS f ON o.ORDER_ID = f.ORDER_ID
)
SELECT
    CUSTOMER_UNIQUE_ID,
    DATEDIFF('day', MAX(PURCHASE_TS), (SELECT MAX_DATE FROM REFERENCE_DATE)) AS RECENCY_DAYS,
    COUNT(DISTINCT ORDER_ID) AS FREQUENCY,
    SUM(ORDER_VALUE) AS MONETARY
FROM CUSTOMER_ORDERS
GROUP BY CUSTOMER_UNIQUE_ID;

SELECT COUNT(*) FROM MARTS.FCT_ORDERS;        -- should be close to 96,000-99,000 (some orders have no items row)
SELECT COUNT(*) FROM MARTS.CUSTOMER_RFM;      -- should be noticeably LESS than 99,441 — that gap is repeat customers