USE DATABASE OLIST_DB;
USE SCHEMA RAW;


SELECT 'RAW.ORDERS: null order_id' AS CHECK_NAME, COUNT(*) AS FAILURES
FROM RAW.ORDERS WHERE ORDER_ID IS NULL

UNION ALL
SELECT 'STAGING.ORDERS: timestamp conversion loss',
       (SELECT COUNT(*) FROM RAW.ORDERS WHERE ORDER_PURCHASE_TIMESTAMP IS NOT NULL)
     - (SELECT COUNT(*) FROM STAGING.ORDERS WHERE PURCHASE_TS IS NOT NULL)

UNION ALL
SELECT 'STAGING.ORDER_ITEMS: price conversion loss',
       (SELECT COUNT(*) FROM RAW.ORDER_ITEMS WHERE PRICE IS NOT NULL)
     - (SELECT COUNT(*) FROM STAGING.ORDER_ITEMS WHERE PRICE IS NOT NULL)

UNION ALL
SELECT 'MARTS.FCT_ORDERS: duplicate order_id', COUNT(*)
FROM (SELECT ORDER_ID FROM MARTS.FCT_ORDERS GROUP BY ORDER_ID HAVING COUNT(*) > 1)

UNION ALL
SELECT 'MARTS.CUSTOMER_RFM: duplicate customer', COUNT(*)
FROM (SELECT CUSTOMER_UNIQUE_ID FROM MARTS.CUSTOMER_RFM GROUP BY CUSTOMER_UNIQUE_ID HAVING COUNT(*) > 1)

UNION ALL
SELECT 'MARTS.DIM_CUSTOMERS: duplicate customer', COUNT(*)
FROM (SELECT CUSTOMER_UNIQUE_ID FROM MARTS.DIM_CUSTOMERS GROUP BY CUSTOMER_UNIQUE_ID HAVING COUNT(*) > 1)

UNION ALL
SELECT 'MARTS.DIM_PRODUCTS: duplicate product_id', COUNT(*)
FROM (SELECT PRODUCT_ID FROM MARTS.DIM_PRODUCTS GROUP BY PRODUCT_ID HAVING COUNT(*) > 1)

UNION ALL
SELECT 'MARTS.DIM_SELLERS: duplicate seller_id', COUNT(*)
FROM (SELECT SELLER_ID FROM MARTS.DIM_SELLERS GROUP BY SELLER_ID HAVING COUNT(*) > 1)

UNION ALL
SELECT 'MARTS.FCT_ORDER_ITEMS: orphaned product_id', COUNT(*)
FROM MARTS.FCT_ORDER_ITEMS f
LEFT JOIN MARTS.DIM_PRODUCTS p ON f.PRODUCT_ID = p.PRODUCT_ID
WHERE p.PRODUCT_ID IS NULL

UNION ALL
SELECT 'MARTS.FCT_ORDER_ITEMS: orphaned seller_id', COUNT(*)
FROM MARTS.FCT_ORDER_ITEMS f
LEFT JOIN MARTS.DIM_SELLERS s ON f.SELLER_ID = s.SELLER_ID
WHERE s.SELLER_ID IS NULL

UNION ALL
SELECT 'MARTS.FCT_ORDERS: orphaned customer_id', COUNT(*)
FROM MARTS.FCT_ORDERS f
LEFT JOIN STAGING.CUSTOMERS c ON f.CUSTOMER_ID = c.CUSTOMER_ID
WHERE c.CUSTOMER_ID IS NULL

UNION ALL
SELECT 'MARTS.FCT_ORDERS: negative order value', COUNT(*)
FROM MARTS.FCT_ORDERS WHERE ORDER_VALUE < 0

UNION ALL
SELECT 'MARTS.CUSTOMER_RFM: negative recency', COUNT(*)
FROM MARTS.CUSTOMER_RFM WHERE RECENCY_DAYS < 0;
