USE DATABASE OLIST_DB;
USE SCHEMA RAW;

CREATE OR REPLACE PROCEDURE SP_REFRESH_STAGING()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

CREATE SCHEMA IF NOT EXISTS OLIST_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS OLIST_DB.MARTS;


-- 1. ORDERS
CREATE OR REPLACE TABLE OLIST_DB.STAGING.ORDERS AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    ORDER_PURCHASE_TIMESTAMP AS PURCHASE_TS,
    ORDER_APPROVED_AT AS APPROVED_TS,
    ORDER_DELIVERED_CARRIER_DATE AS DELIVERED_CARRIER_TS,
    ORDER_DELIVERED_CUSTOMER_DATE AS DELIVERED_TS,
    ORDER_ESTIMATED_DELIVERY_DATE AS ESTIMATED_DELIVERY_TS
FROM OLIST_DB.RAW.ORDERS
WHERE ORDER_ID IS NOT NULL;


-- 2. ORDER ITEMS
CREATE OR REPLACE TABLE OLIST_DB.STAGING.ORDER_ITEMS AS
SELECT
    ORDER_ID,
    ORDER_ITEM_ID,
    PRODUCT_ID,
    SELLER_ID,
    SHIPPING_LIMIT_DATE AS SHIPPING_DATE,
    PRICE,
    FREIGHT_VALUE
FROM OLIST_DB.RAW.ORDER_ITEMS
WHERE ORDER_ID IS NOT NULL
  AND PRODUCT_ID IS NOT NULL;


-- 3. ORDER PAYMENTS
CREATE OR REPLACE TABLE OLIST_DB.STAGING.ORDER_PAYMENTS AS
SELECT
    ORDER_ID,
    PAYMENT_SEQUENTIAL,
    PAYMENT_TYPE,
    PAYMENT_INSTALLMENTS,
    PAYMENT_VALUE
FROM OLIST_DB.RAW.ORDER_PAYMENTS
WHERE ORDER_ID IS NOT NULL;


-- 4. CUSTOMERS
CREATE OR REPLACE TABLE OLIST_DB.STAGING.CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_UNIQUE_ID,
    CUSTOMER_ZIP_CODE_PREFIX,
    INITCAP(CUSTOMER_CITY) AS CUSTOMER_CITY,
    UPPER(CUSTOMER_STATE) AS CUSTOMER_STATE
FROM OLIST_DB.RAW.CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL;


-- 5. SELLERS
CREATE OR REPLACE TABLE OLIST_DB.STAGING.SELLERS AS
SELECT
    SELLER_ID,
    SELLER_ZIP_CODE_PREFIX,
    INITCAP(SELLER_CITY) AS SELLER_CITY,
    UPPER(SELLER_STATE) AS SELLER_STATE
FROM OLIST_DB.RAW.SELLERS
WHERE SELLER_ID IS NOT NULL;


-- 6. PRODUCTS
CREATE OR REPLACE TABLE OLIST_DB.STAGING.PRODUCTS AS
SELECT
    PRODUCT_ID,
    COALESCE(PRODUCT_CATEGORY_NAME, 'unknown') AS PRODUCT_CATEGORY,
    PRODUCT_WEIGHT_G,
    PRODUCT_LENGTH_CM,
    PRODUCT_HEIGHT_CM,
    PRODUCT_WIDTH_CM
FROM OLIST_DB.RAW.PRODUCT
WHERE PRODUCT_ID IS NOT NULL;


-- 7. GEOLOCATION
CREATE OR REPLACE TABLE OLIST_DB.STAGING.GEOLOCATION AS
SELECT
    GEOLOCATION_ZIP_CODE_PREFIX AS ZIP_CODE_PREFIX,
    AVG(GEOLOCATION_LAT) AS LAT,
    AVG(GEOLOCATION_LNG) AS LNG
FROM OLIST_DB.RAW.GEOLOCATION
GROUP BY GEOLOCATION_ZIP_CODE_PREFIX;


-- 8. ORDER REVIEWS
CREATE OR REPLACE TABLE OLIST_DB.STAGING.ORDER_REVIEWS AS
SELECT
    REVIEW_ID,
    ORDER_ID,
    REVIEW_SCORE,
    REVIEW_COMMENT_TITLE,
    REVIEW_COMMENT_MESSAGE,
    REVIEW_CREATION_DATE AS REVIEW_CREATION_TS,
    REVIEW_ANSWER_TIMESTAMP AS REVIEW_ANSWER_TS
FROM OLIST_DB.RAW.ORDER_REVIEWS
WHERE ORDER_ID IS NOT NULL;

    RETURN 'Staging refresh complete';
END;
$$;

CREATE OR REPLACE PROCEDURE SP_REFRESH_MARTS()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

CREATE SCHEMA IF NOT EXISTS OLIST_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS OLIST_DB.MARTS;

CREATE OR REPLACE TABLE MARTS.FCT_ORDERS AS
SELECT
    o.ORDER_ID,
    o.CUSTOMER_ID,
    o.ORDER_STATUS,
    o.PURCHASE_TS,
    o.DELIVERED_TS,
    o.ESTIMATED_DELIVERY_TS,
    DATEDIFF('day', o.ESTIMATED_DELIVERY_TS, o.DELIVERED_TS) AS DELIVERY_DELAY_DAYS,
    CASE
        WHEN o.ORDER_STATUS = 'delivered' AND o.DELIVERED_TS > o.ESTIMATED_DELIVERY_TS THEN 1
        WHEN o.ORDER_STATUS = 'delivered' THEN 0
        ELSE NULL
    END AS IS_LATE,
    oi.ORDER_VALUE,
    oi.FREIGHT_TOTAL,
    oi.ITEM_COUNT
FROM STAGING.ORDERS o
JOIN (
    SELECT ORDER_ID, SUM(PRICE) AS ORDER_VALUE, SUM(FREIGHT_VALUE) AS FREIGHT_TOTAL, COUNT(*) AS ITEM_COUNT
    FROM STAGING.ORDER_ITEMS
    GROUP BY ORDER_ID
) oi ON o.ORDER_ID = oi.ORDER_ID;

CREATE OR REPLACE TABLE MARTS.CUSTOMER_RFM AS
WITH REFERENCE_DATE AS (
    SELECT MAX(PURCHASE_TS) AS MAX_DATE FROM STAGING.ORDERS
),
CUSTOMER_ORDERS AS (
    SELECT
        c.CUSTOMER_UNIQUE_ID,
        o.ORDER_ID,
        o.PURCHASE_TS,
        f.ORDER_VALUE
    FROM STAGING.ORDERS o
    JOIN STAGING.CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
    JOIN MARTS.FCT_ORDERS f ON o.ORDER_ID = f.ORDER_ID
)
SELECT
    CUSTOMER_UNIQUE_ID,
    DATEDIFF('day', MAX(PURCHASE_TS), (SELECT MAX_DATE FROM REFERENCE_DATE)) AS RECENCY_DAYS,
    COUNT(DISTINCT ORDER_ID) AS FREQUENCY,
    SUM(ORDER_VALUE) AS MONETARY
FROM CUSTOMER_ORDERS
GROUP BY CUSTOMER_UNIQUE_ID;

SELECT COUNT(*) FROM MARTS.FCT_ORDERS;        -- should be close to 96,000-99,000 (some orders have no items row)
SELECT COUNT(*) FROM MARTS.CUSTOMER_RFM;      -- should be noticeably LESS than 99,441 — that gap is repeat customers

CREATE OR REPLACE TABLE MARTS.DIM_CUSTOMERS AS
SELECT
    CUSTOMER_UNIQUE_ID,
    CUSTOMER_ZIP_CODE_PREFIX,
    CUSTOMER_CITY,
    CUSTOMER_STATE
FROM STAGING.CUSTOMERS
QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_UNIQUE_ID ORDER BY CUSTOMER_ID) = 1;

CREATE OR REPLACE TABLE MARTS.DIM_SELLERS AS
SELECT SELLER_ID, SELLER_ZIP_CODE_PREFIX, SELLER_CITY, SELLER_STATE
FROM STAGING.SELLERS;

CREATE OR REPLACE TABLE MARTS.DIM_PRODUCTS AS
SELECT PRODUCT_ID, PRODUCT_CATEGORY, PRODUCT_WEIGHT_G, PRODUCT_LENGTH_CM, PRODUCT_HEIGHT_CM, PRODUCT_WIDTH_CM
FROM STAGING.PRODUCTS;

CREATE OR REPLACE TABLE MARTS.FCT_ORDER_ITEMS AS
SELECT
    oi.ORDER_ID, oi.ORDER_ITEM_ID, oi.PRODUCT_ID, oi.SELLER_ID,
    o.CUSTOMER_ID, oi.SHIPPING_DATE, oi.PRICE, oi.FREIGHT_VALUE
FROM STAGING.ORDER_ITEMS oi
JOIN STAGING.ORDERS o ON oi.ORDER_ID = o.ORDER_ID;

    RETURN 'Marts refresh complete';
END;
$$;

CREATE OR REPLACE TASK refresh_staging_task
    WAREHOUSE = OLIST_WH
    SCHEDULE = 'USING CRON 0 6 * * * UTC'
AS
    CALL SP_REFRESH_STAGING();

CREATE OR REPLACE TASK refresh_marts_task
    WAREHOUSE = OLIST_WH
    AFTER refresh_staging_task
AS
    CALL SP_REFRESH_MARTS();

ALTER TASK refresh_marts_task RESUME;

ALTER TASK refresh_staging_task RESUME;

EXECUTE TASK refresh_staging_task;

SELECT NAME, STATE, ERROR_MESSAGE
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME IN ('REFRESH_STAGING_TASK', 'REFRESH_MARTS_TASK')
ORDER BY SCHEDULED_TIME DESC
LIMIT 2;
